
// TAG: surface=api owner=platform-team rule=API-001
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "./AccountType";

/**
 * Financial account information
 */
export type Account = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * User identifier
 */
user_id: string, 
/**
 * Account Type
 */
account_type: AccountType, 
/**
 * Balance
 */
balance: number | null, 
/**
 * Currency
 */
currency: string, 
/**
 * Institution Name
 */
institution_name: string, 
/**
 * Timestamp when the created was created/updated
 */
created_at: string, };
