
// TAG: surface=api owner=platform-team rule=API-001
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Account types supported by `FreshCredit`
 */
export type AccountType = "Checking" | "Savings" | "Credit" | "Investment" | "Loan";
