// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "./AccountType";

/**
 * Financial account information
 */
export type Account = { id: string, user_id: string, account_type: AccountType, balance: number | null, currency: string, institution_name: string, created_at: string, };
