// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountType } from "./AccountType";

/**
 * Financial account information
 */
export type Account = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * User identifier
 */
user_id: string, 
/**
 * Account Type
 */
account_type: AccountType, 
/**
 * Balance
 */
balance: number | null, 
/**
 * Current balance (from Plaid `balances.current`)
 */
current_balance?: number | null, 
/**
 * Available balance (from Plaid `balances.available`)
 */
available_balance?: number | null, 
/**
 * Credit/limit (from Plaid `balances.limit`)
 */
credit_limit?: number | null, 
/**
 * ISO currency code (from Plaid `balances.iso_currency_code`)
 */
iso_currency_code?: string | null, 
/**
 * Account mask (last digits)
 */
mask?: string | null, 
/**
 * Official account name from the institution
 */
official_name?: string | null, 
/**
 * Currency
 */
currency: string, 
/**
 * Institution Name
 */
institution_name: string, 
/**
 * Timestamp when the created was created/updated
 */
created_at: string, };
