// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemDetails } from "./ProblemDetails";
import type { ResponseMeta } from "./ResponseMeta";

/**
 * Standard API response wrapper for single resources
 *
 * This type provides a consistent response format across all API endpoints,
 * addressing the API governance finding of mixed response formats.
 */
export type ApiResponse<T> = { 
/**
 * Whether the request was successful
 */
success: boolean, 
/**
 * The response data (only present on success)
 */
data: T | null, 
/**
 * Error details (only present on error)
 */
error: ProblemDetails | null, 
/**
 * Response metadata (pagination, etc.)
 */
meta: ResponseMeta | null, };
