// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response wrapper
 */
export type ApiResponse<T> = { 
/**
 * Success
 */
success: boolean, 
/**
 * Data
 */
data: T | null, 
/**
 * Error
 */
error: string | null, 
/**
 * Timestamp
 */
timestamp: string, };
