// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { Transaction } from "./Transaction";

/**
 * Financial report data
 */
export type FinancialReport = { id: string, user_id: string, bureau_score: number | null, accounts: Array<Account>, transactions: Array<Transaction>, generated_at: string, blockchain_hash: string | null, };
