// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { Transaction } from "./Transaction";

/**
 * Financial report data
 */
export type FinancialReport = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * User identifier
 */
user_id: string, 
/**
 * Bureau Score
 */
bureau_score: number | null, 
/**
 * Accounts
 */
accounts: Array<Account>, 
/**
 * Transactions
 */
transactions: Array<Transaction>, 
/**
 * Timestamp when the generated was created/updated
 */
generated_at: string, 
/**
 * Blockchain Hash
 */
blockchain_hash: string | null, };
