// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard pagination query parameters
 *
 * Use this struct as an Axum extractor for consistent pagination
 * across all list endpoints.
 *
 * # Example
 * ```ignore
 * use axum::extract::Query;
 *
 * async fn list_users(
 *     Query(pagination): Query<PaginationQuery>,
 * ) -> impl IntoResponse {
 *     let pagination = pagination.validate();
 *     let offset = pagination.offset();
 *     let limit = pagination.limit();
 *     // ... fetch users
 * }
 * ```
 */
export type PaginationQuery = { 
/**
 * Page number (1-indexed, default: 1)
 */
page: number, 
/**
 * Items per page (default: 20, max: 100)
 */
per_page: number, 
/**
 * Cursor for cursor-based pagination
 *
 * When provided, `page/per_page` are ignored
 */
cursor: string | null, };
