
// TAG: surface=api owner=platform-team rule=API-001
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RFC 7807 Problem Details for HTTP APIs
 */
export type ProblemDetails = { 
/**
 * Problem Type
 */
type: string, 
/**
 * Title
 */
title: string, 
/**
 * Status
 */
status: number, 
/**
 * Detail
 */
detail: string | null, 
/**
 * Instance
 */
instance: string | null, 
/**
 * Request identifier
 */
request_id: string | null, };
