// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RFC 7807 Problem Details for HTTP APIs
 */
export type ProblemDetails = { type: string, title: string, status: number, detail: string | null, instance: string | null, request_id: string | null, };
