// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response metadata for pagination and filtering
 *
 * Provides consistent pagination information across all list endpoints.
 */
export type ResponseMeta = { 
/**
 * Total number of items available (for offset pagination)
 */
total_count: bigint | null, 
/**
 * Number of items returned in this response
 */
returned_count: number, 
/**
 * Current page number (1-indexed, for offset pagination)
 */
page: number | null, 
/**
 * Items per page (for offset pagination)
 */
per_page: number | null, 
/**
 * Cursor for cursor-based pagination
 */
next_cursor: string | null, 
/**
 * API version used for this response
 */
api_version: string, 
/**
 * Request ID for tracing and debugging
 */
request_id: string, };
