
// TAG: surface=api owner=platform-team rule=API-001
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Financial transaction
 */
export type Transaction = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Account identifier
 */
account_id: string, 
/**
 * Amount
 */
amount: number, 
/**
 * Currency
 */
currency: string, 
/**
 * Description
 */
description: string, 
/**
 * Category
 */
category: string | null, 
/**
 * Date
 */
date: string, 
/**
 * Merchant Name
 */
merchant_name: string | null, };
