// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Financial transaction
 */
export type Transaction = { id: string, account_id: string, amount: number, currency: string, description: string, category: string | null, date: string, merchant_name: string | null, };
