[package]
name = "freshcredit-libsql-local"
version.workspace = true
edition.workspace = true
license.workspace = true

repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
[features]
default = []
test-utils = []

[dependencies]
libsql = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }

# Internal dependencies
freshcredit-types = { path = "../../../core/types", version = "0.1.0" }
freshcredit-libsql-common = { path = "../common", version = "0.1.0" }
workspace-hack = { version = "0.1", path = "../../../../workspace-hack" }

[dev-dependencies]
sha2 = "0.10"
hex = { workspace = true }
urlencoding = "2.1"
base64 = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]
