[package]
name = "freshcredit-libsql-cloud"
version.workspace = true
edition.workspace = true
license.workspace = true

repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
[dependencies]
libsql = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

# Internal dependencies
freshcredit-types = { workspace = true }
freshcredit-libsql-local = { workspace = true }
freshcredit-libsql-common = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]
